### ISSUE TITLE
Email Addresses only added to set of per-products lists per order

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-activecampaign#32]
Expected:
If more than on product is purchase, email addresses should be added to all selected per-products lists for all purchased products.

Actual:
Email only added to 1 product's per-product lists.

Example:
Product A has List 1 and List 2 selected.
Product B has List 3 selected.

When purchasing both Product A & B in the same order, email address should be added to Lists 1, 2 AND 3.

But, email is only added to List 1 and 2.

Steps:
1. Enable active campaign, select Master list for the default list.
2. Create 3 more lists in Active Campaign
3. Assign 2 lists to one product. (technically 1 list should be valid, but customer has multiple lists selected)
4. Assign the other list to another product.
5. Test a purchase of both products in the same order. Also, opt-in to email list on checkout.

**Comment by ashleyfae** [comment]
I'm looking at this and I think we need to rework the whole `completed_download_purchase_signup()` method.

We hook into `edd_complete_download_purchase`. That fires _once per product in the cart_. Now the issue is that we only do anything if the user's meta exists: https://github.com/easydigitaldownloads/edd-activecampaign/blob/master/edd-activecampaign.php#L650 That's fine. But after running this once, we delete that meta: https://github.com/easydigitaldownloads/edd-activecampaign/blob/master/edd-activecampaign.php#L696 That means when the method fires a second time for the second product in the cart, the meta is gone.

I think we should update our code to use `edd_after_payment_actions` instead.

1. That means the customer doesn't have to sit and wait for this to happen.
2. That's one action that will be triggered, at which point we'll add the user to all lists at once.
